# Generated by Django 5.2 on 2025-05-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_split_values_expensesplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='split_values',
        ),
    ]
